#!/bin/bash

REPO=$JENKINS_HOME/bootable-clang-built-debian
PATCHES=$REPO/patches

rm $JENKINS_HOME/packages/*${1}*
mkdir $1
cd $1
apt-get source $1
if [ -e $PATCHES/${1}_clang.patch ]
then 
	patch -p0 < $PATCHES/${1}_clang.patch
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	cd `ls -l | grep ^d | head -n1 | awk '{print $9}'`
	if [ $2 = "special" ]
	then 
		sudo pdebuild --buildresult $WORKSPACE --use-pdebuild-internal -- --basetgz /var/cache/pbuilder/base-sid-normal-amd64.tgz
	else
		sudo pdebuild --buildresult $WORKSPACE --use-pdebuild-internal -- --basetgz /var/cache/pbuilder/base-sid-clang-amd64.tgz
	fi
else
	if [ $2 = "special" ]
	then
		sudo pbuilder --build  --buildresult $WORKSPACE --basetgz /var/cache/pbuilder/base-sid-normal-amd64.tgz *dsc
	else
		sudo pbuilder --build  --buildresult $WORKSPACE --basetgz /var/cache/pbuilder/base-sid-clang-amd64.tgz *dsc
	fi
fi
RES=$?
sudo rm -r $WORKSPACE/$1
exit $RES
