#!/bin/bash

REPO_DIR=/var/www/debian
PACKAGE_LIST=$WORKSPACE/linux_package.list
BASE=$WORKSPACE/llvmlinux/targets/x86_64
KERNEL_SRC=$BASE/src/linux
CONFIG_DIR=$BASE/build/kernel-clang

cd $BASE
git pull
make kernel-sync
cd $KERNEL_SRC
KERNEL_NEW=`make kernelversion`
KERNEL_OLD=`cat $WORKSPACE/kernel_version`
if [ $KERNEL_NEW = $KERNEL_OLD ]; then exit 0; fi
echo $KERNEL_NEW > $WORKSPACE/kernel_version
cd $BASE
make kernel-patch
make kernel-configure
cp -r $KERNEL_SRC $WORKSPACE
cp $CONFIG_DIR/.config $WORKSPACE/linux
cd $WORKSPACE/linux
make ARCH=x86_64 -l1 -j2 CONFIG_DEBUG_INFO=1 CONFIG_DEBUG_SECTION_MISMATCH=y CONFIG_NO_ERROR_ON_MISMATCH=y HOSTCC="/var/lib/jenkins/jobs/llvmlinux_clang_built/workspace/llvmlinux/toolchain/clang/head/install/bin/clang" CC="/var/lib/jenkins/jobs/llvmlinux_clang_built/workspace/llvmlinux/toolchain/clang/head/install/bin/clang" deb-pkg
RES=$?
rm -r $WORKSPACE/linux
cd $BASE
make clean-all
if [ $RES -ne 0 ]; then exit 1; fi
cd $REPO_DIR
sudo reprepro remove clang-built `cat $PACKAGE_LIST`
sudo reprepro includedeb clang-built $WORKSPACE/*deb
ls $WORKSPACE/*deb > $PACKAGE_LIST
