#!/bin/bash

IMG=$1
LINUX=`apt-cache search -t sid linux-image | grep "for 64-bit PCs$" | head -1 | awk -F" - " '{print $1}'` 
INCLUDE="--include=$LINUX,grub-pc,locales,ifupdown,isc-dhcp-client,openssh-server"
VARIANT="--variant=minbase"
MIRROR="http://http.debian.net/debian" 
HOSTNAME="clang-built"

# create image file and install system with debootstrap
sudo qemu-img create -f qcow2 ${IMG}.qcow2 5G
mkdir $IMG
sudo modprobe nbd max_part=16
sudo qemu-nbd -c /dev/nbd0 ${IMG}.qcow2
sudo partprobe /dev/nbd0
echo -e "o\nn\n\n\n\n\na\nw\n" | sudo fdisk /dev/nbd0
sudo mkfs.ext4 -q /dev/nbd0p1
sudo mount /dev/nbd0p1 $IMG 
sudo debootstrap $VARIANT $INCLUDE sid $IMG $MIRROR
if [ $? -ne 0 ]; then exit 1; sudo umount $IMG; sudo qemu-nbd -d /dev/nbd0; fi

# make some configuration
cat <<EOF > $IMG/etc/fstab
/dev/sda1 /                   ext4    errors=remount-ro 0       1
EOF
echo $HOSTNAME > $IMG/etc/hostname
cat <<EOF > $IMG/etc/hosts
127.0.0.1       localhost
127.0.1.1 		$HOSTNAME
# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
cat <<EOF > $IMG/etc/network/interfaces
auto lo
iface lo inet loopback
auto enp0s3
iface enp0s3 inet dhcp
EOF

# make further configuration and replace all packages with clang-built version
sudo LC_ALL=C arch-chroot $IMG /bin/bash -x <<'EOF'
source /etc/profile
locale-gen en_US en_US.UTF-8
echo -e "LANGUAGE=en_US.UTF-8\nLANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8" >> /etc/profile
apt-get --yes remove gcc-4.8-base gcc-4.9-base
echo -e "no\n" | apt-get --yes remove `dpkg -l | grep linux-image | awk '/^ii/ {print $2}' | head -1`
echo "deb http://128.199.87.18/debian/ clang-built main" > /etc/apt/sources.list
apt-get update
ALL_PACKAGE=`dpkg -l | awk '/^ii/ {print $2}' | grep -v "apt\|grub\|gcc"`
for PKG in $ALL_PACKAGE; do apt-get --yes --force-yes --reinstall install $PKG=`apt-cache showpkg $PKG | grep "^[0-9]" | grep "/var/lib/apt/lists/128.199.87.18_debian_dists_clang-built_main_binary-amd64_Packages" | awk '{print $1}'`; done
apt-get --yes --force-yes upgrade
apt-get --yes --force-yes install `apt-cache search linux-image | awk -F" - " '{print $1}'`
DEBIAN_FRONTEND=noninteractive apt-get --yes --force-yes --reinstall install grub-pc=`apt-cache showpkg grub-pc | grep "^[0-9]" | grep "/var/lib/apt/lists/128.199.87.18_debian_dists_clang-built_main_binary-amd64_Packages" | awk '{print $1}'` 
grub-install /dev/nbd0
update-grub
echo -e "root\nroot\n" | passwd
systemctl enable ssh
useradd -m -s /bin/bash user
echo -e "user\nuser\n" | passwd user
EOF
sed -i "s|/dev/nbd0p1|/dev/sda1|g" $IMG/boot/grub/grub.cfg
sudo umount $IMG

# test bootablity with ssh
sudo qemu-nbd -d /dev/nbd0
qemu-system-x86_64 -m 128 -hda bootable.qcow2 -nographic -net user,hostfwd=tcp::8964-:22 -net nic -enable-kvm < /dev/null &
sudo ssh-keygen -f "/root/.ssh/known_hosts" -R [localhost]:8964
sleep 30
sshpass -p "user" ssh -o StrictHostKeyChecking=no -p 8964 user@localhost << EOF
logout
EOF
RES=$?
killall -9 qemu-system-x86_64
if [ $RES -eq 0 ]
then 
	tar -Jcf ${1}.tar.xz ${1}.qcow2
	rm ${1}.qcow2
else
	rm ${1}.qcow2
	exit 1
fi
