#!/bin/bash

IMG=$1
LINUX=`apt-cache search -t sid linux-image | grep "for 64-bit PCs$" | head -n1 | awk -F" - " '{print $1}'` 
INCLUDE="--include=$LINUX,grub-pc,locales,ifupdown"
VARIANT="--variant=minbase"
MIRROR="http://mirrors.163.com/debian" 

sudo qemu-img create -f qcow2 ${IMG}.qcow2 5G
mkdir $IMG
sudo modprobe nbd max_part=16
sudo qemu-nbd -c /dev/nbd0 ${IMG}.qcow2
sudo partprobe /dev/nbd0
echo -e "o\nn\n\n\n\n\na\nw\n" | sudo fdisk /dev/nbd0
sudo mkfs.ext4 /dev/nbd0p1
sudo mount /dev/nbd0p1 $IMG 
sudo debootstrap $VARIANT $INCLUDE sid $IMG $MIRROR
RES=$?

sudo arch-chroot $IMG /bin/bash -x <<'EOF'
source /etc/profile
sed -i 's/# en_US.UTF-8/ en_US.UTF-8/g' /etc/locale.gen
locale-gen 
echo -e "LANGUAGE=en_US.UTF-8\nLANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8" >> /etc/environment
KERNEL=`dpkg -l | grep linux-image | awk '/^ii/ {print $2}' | head -1`
apt-get --yes remove gcc-4.8-base gcc-4.9-base
echo "deb http://128.199.87.18/debian/ clang-built main" > /etc/apt/sources.list
apt-get update
apt-get --yes --force-yes upgrade
apt-get --yes --force-yes install `apt-cache search linux-image | awk -F" - " '{print $1}'`
echo -e "no\n" | apt-get --yes remove $KERNEL
grub-install /dev/nbd0
update-grub
EOF

sudo umount $IMG
sudo qemu-nbd -d /dev/nbd0
exit $RES
