#!/bin/bash

REPO=$JENKINS_HOME/bootable-clang-built-debian
PKG_LIST=$JENKINS_HOME/userContent/package.list
UPDATE_NUM=0

cd $REPO
git pull
sudo apt-get update
cd $WORKSPACE
while read PKG
do
	NEW_VERSION=`apt-cache showsrc $PKG | awk -F": " '/^Version/ {print $2}' | tail -1`
	if [ -e ${PKG}_version ]
	then
		OLD_VERSION=`cat ${PKG}_version`
	else
		OLD_VERSION="none"
	fi
	LAST_RESULT=`/usr/bin/jenkins-driver last-result ${PKG}_clang_built | grep -c SUCCESS`
	if [ $NEW_VERSION != $OLD_VERSION ] || [ $LAST_RESULT -ne 1 ]
	then
		echo $NEW_VERSION > ${PKG}_version
		UPDATE_NUM=`expr $NUM + 1`
		/usr/bin/jenkins-driver build ${PKG}_clang_built wait
	fi
done < $PKG_LIST

/usr/bin/jenkins-driver build llvmlinux wait
JOBS=`/usr/bin/jenkins-driver all-jobs | grep -v start_clang_built | grep -c clang_built`
SUCCEEDED=`/usr/bin/jenkins-driver all-jobs | grep -v start_clang_built | grep clang_built | grep -c blue`
if [ $JOBS -ne $SUCCEEDED ]
then
	exit 1
else
	if [ $UPDATE_NUM -gt 0 ]
	then
		/usr/bin/jenkins-driver build 1_publish_respository nowait
	fi
fi
